import { ROLES, type Role, type Action, type Resource, ACTIONS, RESOURCES } from '@/config/roles';

// Permission Matrix defining what actions each role can perform on what resources
export const PERMISSIONS: Record<Role, Partial<Record<Resource, Action[]>>> = {
  [ROLES.SUPER_ADMIN]: {
    [RESOURCES.ALL]: [ACTIONS.MANAGE],
  },
  [ROLES.ADMIN]: {
    [RESOURCES.PATIENT]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.STAFF]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.BRANCH]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.DEPARTMENT]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.AUDIT_LOG]: [ACTIONS.READ],
    // Admins usually have wide access
  },
  [ROLES.DOCTOR]: {
    [RESOURCES.PATIENT]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.APPOINTMENT]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.VISIT]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.DIAGNOSIS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.MEDICAL_RECORD]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.PRESCRIPTION]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.LAB_REQUEST]: [ACTIONS.CREATE, ACTIONS.READ],
    [RESOURCES.LAB_RESULT]: [ACTIONS.READ],
    [RESOURCES.RADIOLOGY_REQUEST]: [ACTIONS.CREATE, ACTIONS.READ],
    [RESOURCES.RADIOLOGY_REPORT]: [ACTIONS.READ],
    [RESOURCES.ADMISSION]: [ACTIONS.CREATE, ACTIONS.READ],
    [RESOURCES.SURGERY]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.DOCUMENT]: [ACTIONS.CREATE, ACTIONS.READ],
  },
  [ROLES.NURSE]: {
    [RESOURCES.PATIENT]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.MEDICAL_RECORD]: [ACTIONS.CREATE, ACTIONS.READ],
    [RESOURCES.ADMISSION]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.PRESCRIPTION]: [ACTIONS.READ],
    [RESOURCES.LAB_RESULT]: [ACTIONS.READ],
  },
  [ROLES.RECEPTIONIST]: {
    [RESOURCES.PATIENT]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.APPOINTMENT]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.INVOICE]: [ACTIONS.CREATE, ACTIONS.READ],
    [RESOURCES.PAYMENT]: [ACTIONS.CREATE, ACTIONS.READ],
  },
  [ROLES.PHARMACIST]: {
    [RESOURCES.PATIENT]: [ACTIONS.READ],
    [RESOURCES.PRESCRIPTION]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.MEDICINE]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.INVENTORY]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
  },
  [ROLES.LAB_SCIENTIST]: {
    [RESOURCES.PATIENT]: [ACTIONS.READ],
    [RESOURCES.LAB_REQUEST]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.LAB_RESULT]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
  },
  [ROLES.RADIOGRAPHER]: {
    [RESOURCES.PATIENT]: [ACTIONS.READ],
    [RESOURCES.RADIOLOGY_REQUEST]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.RADIOLOGY_REPORT]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
  },
  [ROLES.ACCOUNTANT]: {
    [RESOURCES.PATIENT]: [ACTIONS.READ],
    [RESOURCES.INVOICE]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.PAYMENT]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.STAFF]: [ACTIONS.READ],
  },
  [ROLES.THEATRE_STAFF]: {
    [RESOURCES.PATIENT]: [ACTIONS.READ],
    [RESOURCES.SURGERY]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
  },
  [ROLES.MATERNAL_STAFF]: {
    [RESOURCES.PATIENT]: [ACTIONS.READ],
    [RESOURCES.MATERNAL_RECORD]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
  },
  [ROLES.MENTAL_HEALTH]: {
    [RESOURCES.PATIENT]: [ACTIONS.READ],
    [RESOURCES.PSYCH_ASSESSMENT]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.THERAPY_SESSION]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
  },
  [ROLES.AMBULANCE]: {
    [RESOURCES.PATIENT]: [ACTIONS.READ],
  },
  [ROLES.PATIENT]: {
    [RESOURCES.PATIENT]: [ACTIONS.READ],
    [RESOURCES.APPOINTMENT]: [ACTIONS.CREATE, ACTIONS.READ],
    [RESOURCES.MEDICAL_RECORD]: [ACTIONS.READ],
    [RESOURCES.PRESCRIPTION]: [ACTIONS.READ],
    [RESOURCES.LAB_RESULT]: [ACTIONS.READ],
    [RESOURCES.INVOICE]: [ACTIONS.READ],
    [RESOURCES.PAYMENT]: [ACTIONS.READ],
  },
};

/**
 * Check if a role has a specific permission on a resource.
 */
export function canAccess(role: Role, resource: Resource, action: Action): boolean {
  if (role === ROLES.SUPER_ADMIN) return true;

  const rolePermissions = PERMISSIONS[role];
  if (!rolePermissions) return false;

  const resourcePermissions = rolePermissions[resource];
  if (!resourcePermissions) return false;

  return resourcePermissions.includes(action) || resourcePermissions.includes(ACTIONS.MANAGE);
}
